[package]
name = "fyp-core"
description = "4YouPDF document engine: PDF syntax, object model, xref, filters, writer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
