[package]
name = "fyp-crypto"
description = "Standard security handler: RC4, AES-128/256, PDF 2.0 revision 6"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
aes = "0.8"
cbc = "0.1"
md-5 = "0.10"
rc4 = "0.1"
sha2 = "0.10"

[lints]
workspace = true
