name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build -p fyp-cli --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: fyp-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/fyp*

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: orhun/git-cliff-action@v4
        with:
          args: --latest --strip header
        id: cliff
      - uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.cliff.outputs.content }}
